### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by LFF5644** [L3P3/minicrust#1]
clients must me compertieble with windows nobody has linux desktop all use windows for GUI things and linux as server/terminal things or is you game written in a terminal ???

**Comment by LFF5644** [comment]
LABEL: BUG

**Comment by L3P3** [comment]
Maybe later! This is just an experiment!

**Comment by L3P3** [comment]
Später will ich normale Fenster unterstützen und dann kann ich das auch für Windows machen, vielleicht.

**Comment by L3P3** [comment]
@odincat Hilf ma
